# Generated by Django 6.0.5 on 2026-05-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_date', models.DateField()),
                ('cycle_length', models.IntegerField(default=28)),
            ],
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
