# Generated by Django 6.0.5 on 2026-05-28 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_periodentry_delete_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
